server:
  compression:
    enabled: true
  max-http-header-size: 16384
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

--- # test profile
spring:
  datasource:
    url: jdbc:h2:mem:testDatabase;MODE=PostgreSQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  #    url: jdbc:postgresql://localhost:5433/test
  #    username:
  #    password:
  #    driver-class-name: org.postgresql.Driver
  output:
    ansi:
      enabled: always
  profiles: test
